#!/usr/bin/env python3
"""GOLD batch 3 — 15 more vivid, prompt-matched scripts (45 total candidates; gold 57->72).
Unique openings enforced against EVERYTHING already in A_gold.jsonl and _candidates/.
Appends to _candidates/ + A_gold.jsonl (with intake=prompt), rebuilds INDEX.md."""
import json
from pathlib import Path

CAND = Path.home()/"Downloads/hearth-corpus/A-imagination/_candidates"
GOLD = Path.home()/"Downloads/hearth-corpus/A-imagination/A_gold.jsonl"

SCRIPTS = [
("the-childhood-kitchen", "being back in my grandmother's kitchen while she cooks",
"Come to rest, and let your eyes close on their own time. … Let this room fade, and an older, warmer one rise. …… You are small again, sitting at the kitchen table while your grandmother cooks. … The table's surface is worn smooth under your hands; you know its every scratch. … The whole room is warm from the stove, and full of the sound of her working — the knife on the board, steady and unhurried; a pot lid chattering softly; her voice humming something under her breath, half to you, half to the food. …… And the smell. It hits you all at once, the way only childhood smells do — onions going gold in butter, something baking, the particular soap-and-flour smell of her apron when she passes behind your chair and rests a hand on your head for a second without even pausing. … Steam fogs the window over the sink. The light in here is yellower than light is now. … Nothing is asked of you in this kitchen. You are fed here, and safe here, and hers here. … Watch her work as long as you like. ……\n\nNow let the kitchen grow soft and golden at the edges. … Keep the hand on your head; keep the warmth. … Come back slowly to your own kitchen, your own year, your chair. … Open your eyes when you are ready."),
("the-waterfall-pool", "swimming in a jungle pool under a waterfall",
"Breathe out long, and let your eyes fall closed on the exhale. … Let the air around you turn green and warm. …… You are treading water in a deep, clear pool at the base of a waterfall, somewhere lush and far away. … The water is cool silk against your whole body, clean as glass; below you, your legs scull pale green in the underwater light. … And in front of you the fall comes down — a white column pounding into the pool, throwing up a constant cool mist that beads on your face and lashes. …… The sound is everywhere, a heavy soft roar that swallows every thought. … Swim closer. Feel the current push gently back at you, the mist thicken, the roar deepen in your chest. … Now slip through the edge of the curtain — one cold hammering second — and you're behind it, in the hidden room of rock, where the light comes through the falling water all silver-green and the roar goes hollow. … You're grinning; you can feel it. … Float here, hidden behind the world's loudest curtain, in on the secret. ……\n\nNow drift back out through the bright water. … Keep the cool, the roar, the grin. … Come back to your breath, your chair, the dry quiet room. … Open your eyes when you are ready."),
("the-finish-line", "crossing the finish line of the race I trained a year for",
"Settle your weight down into the chair and let your eyes shut. … Feel your heart beat once, twice — steady. Now let it become a different heartbeat. …… You are in the last half-mile of the race you trained a whole year for. … Your legs are past burning into something clean and mechanical; your breath saws in a rhythm you know like your own name; your feet strike, strike, strike. … The crowd noise has been a blur for a mile, and now it starts to sharpen — you can pick out single voices, a cowbell, your name. …… And there it is: the finish arch, closer every stride. … Everything you gave up for this — the dark-morning runs, the sore weeks, the doubt — is suddenly all here at once, carrying you. … You find one more gear you didn't know you had. … The line comes up — and you're across. … Stop. Bend. Hands on knees, chest heaving, someone's hand thumping your back. … A year of your life, and you did it. Let it break over you like a wave. ……\n\nNow let the crowd soften and the pounding ease. … Keep the earned, emptied-out, brimming feeling. … Come back to your slow breath, your still body, the chair. … Open your eyes when you are ready."),
("the-greenhouse-rain", "puttering in a warm greenhouse while it rains",
"Let your hands rest, let your eyes close, and let the light behind them go green. …… You are in a small greenhouse, and it is raining. … The rain drums soft and steady on the glass overhead, streaming down the panes in bright ropes, and inside everything is warm and green and breathing. … The air is thick with the smell of wet soil and tomato leaves and geranium — that green, growing smell that gets into your chest and loosens it. …… You are puttering. No plan. … You press a finger into the soil of one pot — cool, damp, alive. … You pinch off a yellowed leaf. You turn a seedling a quarter-turn toward the light. … Water drips somewhere off a bench, unhurried. … Every surface is crowded with growing things leaning toward the grey bright glass, and the rain keeps up its long soft drumming, and there is nothing in here that needs you to be anyone but this — a pair of warm hands moving slowly among plants. … Stay and putter. ……\n\nNow let the green blur softly and the drumming recede. … Keep the loose chest and the smell of rain and soil. … Come back to your own hands, your breath, the chair. … Open your eyes when you are ready."),
("the-night-train-sleeper", "falling asleep in a sleeper car as the train rolls through the dark",
"Let yourself lean back until something holds you, and close your eyes. … Feel a gentle motion begin, side to side, like something rocking you. …… You are in a narrow bunk in a sleeper car, and the train is rolling through the night. … The blanket is heavy and tucked; the pillow is cool; the whole little room sways in a rhythm old as rocking itself. … Beneath you the wheels keep their long iron lullaby — da-dum-da-dum … da-dum-da-dum — mile after mile after mile. …… Through the window past your feet, the dark country slides by: a farm light far off, a moonlit field, the sudden close rush of trees, then open dark again. … Somewhere a crossing bell blooms and fades. … You are being carried. You don't have to steer, or watch, or wake — the train knows the way, and every mile is taken care of. … Let the sway loosen your shoulders. Let the wheels count for you. … Heavier now. Warmer now. Carried. ……\n\nNow, without losing the heaviness, let the train slow toward your own room. … Keep the rocking calm in your body. … Feel the chair beneath you, your breath slow and deep. … Open your eyes gently, when you are ready."),
("the-first-snow-walk", "being the first person to walk through fresh overnight snow",
"Stand still inside yourself for a moment, and let your eyes close. … Let the air go cold and bright and new. …… You step out into a morning after overnight snow, and you are the first one out in it. … The whole street is one unbroken sheet of white — no footprints, no tire tracks, nothing but a clean page laid over the world. … The sky is that pale scoured blue that comes after a storm, and the light off the snow is so bright it rings. …… You take the first step, and the snow gives under your boot with that deep, clean creak — the most satisfying sound winter makes. … Another step. Another. You look back: yours are the only tracks in the world. … The trees stand loaded and glittering, dropping soft bombs of powder when the breeze moves them. Your breath plumes. Your cheeks sting in the good way. … Everything ordinary — the mailbox, the hedge, the parked cars — has been made new and strange and beautiful overnight. … Walk the clean page as far as you like. ……\n\nNow let the bright white soften. … Keep the ringing light and the clean creak of that first step. … Come back to your warm breath, your body, the chair. … Open your eyes when you are ready."),
("the-harbor-morning", "drinking coffee on a dock while a small harbor wakes up",
"Wrap both hands around something warm in your mind, and let your eyes close. …… You are sitting at the end of a dock in a small harbor, early, with a hot cup in your hands. … The water is calm as poured metal, and the moored boats ride it barely moving, their masts ticking and clinking softly in the little air. … Gulls stand one-legged on the pilings, unbothered. …… The harbor is waking around you in small sounds: a halyard slapping somewhere, a screen door, an engine turning over across the water and settling into a putter, two fishermen talking low as they load a skiff. … The coffee is strong and hot and tastes better out here than it ever does inside. … Light comes up slow behind the hills and lays itself out across the water toward you, and the boats go from grey to white to their own colors. … Nobody needs you to do anything but sit here and hold the warm cup and watch a small world begin its day. ……\n\nNow let the harbor sounds recede like a tide. … Keep the warm cup and the unhurried morning. … Come back to your breath, your chair, your own day — no rush. … Open your eyes when you are ready."),
("the-library-late", "alone in a great library late at night, one lamp on",
"Let your eyes close the way a heavy book closes — slowly, with weight. …… You are alone in a great old library, late at night, and you have permission to be here. … One green-shaded lamp burns at your table; everything beyond its pool of gold is tall shadow — stacks rising into the dark, spines by the hundred thousand, all that patient thought asleep on its shelves. …… The silence in here has texture. It's made of paper and old wood and years. … Your chair creaks; the sound travels and dies somewhere among the stacks. … On the table before you: the one book you came for, open, and your own notes beside it. … The words are going in clean tonight — that rare late-night clarity where every sentence clicks into place like a key turning. … Around you the dark shelves stand like a city that trusts you alone inside it. … Read. Take your time. The night is long and it is all yours. ……\n\nNow mark your place and let the lamp dim gently. … Keep the clarity and the deep shelved quiet. … Come back to your breath, your chair, the present room. … Open your eyes when you are ready."),
("the-olive-grove", "an afternoon nap under olive trees in the Mediterranean heat",
"Let the light behind your eyelids go white-gold and hot, and settle back. …… You are lying in the dry grass under an olive tree, somewhere Mediterranean, in the deep still heat of early afternoon. … The shade is exactly deep enough. Where it ends, the sunlight lies on the ground like something solid. … The heat has silenced almost everything — just the cicadas, that endless shimmering ratchet, so constant it becomes the sound of the heat itself. …… The grass is warm and dry and smells of dust and thyme. … Above you the olive leaves stir in a breath of wind, silver-green, and their small shadows swim over your arms. … Far off, a dog barks twice and gives up. A church bell rings once for the half hour and the silence closes back over it. … Nothing will happen for hours. Nothing is supposed to. … The whole hot world has agreed to stop, and you with it. … Let your thoughts slow to the speed of the leaves. ……\n\nNow let the cicadas fade to a hush. … Keep the warmth and the enormous unhurried stillness. … Come back to your breath, your body, the cool room. … Open your eyes when you are ready."),
("the-bonfire-beach-night", "a driftwood bonfire on the beach after everyone's gone home",
"Let your eyes close and find a point of warmth in the dark. …… You are on a beach at night, beside a driftwood bonfire, after everyone else has gone home. … The fire has burned down past its loud stage into its best one — deep orange, hissing softly, collapsing now and then into caves of ember. … Its heat presses on your face and shins; at your back, the night ocean breathes in and out, unseen, enormous. …… Salt and woodsmoke. The sand under you still holds a little of the day's warmth. … Sparks rise when a log settles, drift sideways on the sea wind, and go out among stars they briefly imitated. … You poke the fire just to see it flare. … The waves keep arriving, one after another after another, patient as breathing, and the fire keeps ticking down, and nobody in the world knows exactly where you are right now — which, tonight, is not loneliness; it's freedom. … Stay until the embers go jewel-red. ……\n\nNow bank the fire in your mind and let the beach soften. … Keep the ember-warmth and the sound of the patient waves. … Come back to your breath, your chair, the still room. … Open your eyes when you are ready."),
("becoming-the-whale", "being a whale, huge and slow, in deep open ocean",
"Take the deepest breath you've taken all day, and let your eyes close as you release it. … Let yourself grow larger with the next one. …… You are a whale. … Not watching one — being one: forty tons of slow grace hanging in the blue-lit open ocean, weightless as a thought. … Feel the sheer size of yourself, and how gently you carry it. One easy sweep of your flukes and the water pours past your whole length. …… Below you the blue goes down through violet into black, and it doesn't frighten you; it's home. … Light from the surface falls around you in long moving shafts. … You sing — feel it rise out of you, impossibly deep, and roll out into the dark for miles, and wait … and from somewhere beyond seeing, an answer comes back through the water and hums in your bones. … You are enormous, unhurried, and utterly unafraid. Nothing in the ocean hurries you. Nothing ever has. … Rise now, slow as a held note, toward the bright ceiling — and break it, and breathe. ……\n\nNow let the ocean hand you gently back to your own size. … Keep the unhurried hugeness, the unafraid depth. … Come back to your own breath, your body, the chair. … Open your eyes when you are ready."),
("the-orchard-ladder", "picking apples high on an orchard ladder in October",
"Let your eyes close, and reach one hand up into the imagined air. …… You are near the top of a wooden ladder leaned into an apple tree, deep in an orchard, in October. … The ladder creaks its old creak as you shift; the branch before you is heavy with fruit, red-and-gold globes crowding the leaves. … You twist one free — that perfect small snap — and its weight fills your palm, cool from the morning, waxy-smooth. …… The whole orchard smells of it: cider-sweet, sun on grass, a ghost of woodsmoke from somewhere over the hill. … Below you the rows run long and gold-lit, ladders and buckets dotted down them, someone laughing three trees over. … You polish the apple once on your sleeve — the old gesture, automatic — and bite it. Loud, cold, sweet-sharp, the best one you'll ever eat because you're eating it in the tree it grew on. … Above you, more branches, more fruit, more blue October air. Pick as long as the morning lasts. ……\n\nNow climb down slow, rung by rung, back toward your chair. … Keep the snap, the sweetness, the gold light down the rows. … Come back to your breath, your hands, the room. … Open your eyes when you are ready."),
("the-hot-shower-after", "the long hot shower after being cold and wet all day",
"Let your shoulders climb toward your ears — hold them there a second — and now let them fall as your eyes close. …… You have been cold and wet all day, chilled down to the bone-deep place — and now you step into a hot shower. … The water hits the back of your neck and you actually gasp. … Heat floods down your back, your arms, your legs; the cold retreats before it like a tide going out. …… Steam billows and thickens until the whole small room is a warm cloud. … You turn, and the heat takes your chest, your face, your scalp. … You can feel each separate muscle that had clenched itself against the cold discover, one by one, that it can stop now. Neck. Shoulders. The small of your back. Even your hands. … You just stand there. That's the whole activity: standing in hot water, being returned to yourself. … The drumming heat, the steam, the smell of soap, the fog on the glass. Stay until the last of the chill is a memory. ……\n\nNow let the water taper off, wrapped in an enormous imagined towel. … Keep the warmed-through, returned-to-yourself ease. … Come back to your dry, warm, breathing body in the chair. … Open your eyes when you are ready."),
("the-rooftop-garden-dawn", "watering a rooftop garden as the city wakes below",
"Stand quietly inside yourself, let your eyes close, and rise a few storeys. …… You are on a rooftop at dawn, watering a garden you built above a city. … The watering can is heavy and cool in your hand; the water arcs and patters into pots of tomatoes and basil and climbing beans, and the smell of wet soil rises up like the garden saying thank you. …… Around and below you, the city is still mostly asleep — soft grey towers, a few early windows lit, the streets' first murmur drifting up thin and far away. … The sky in the east is going peach behind the rooftops and water tanks. … A pigeon regards you from the parapet like a neighbor. … Up here you've made a secret: green and growing, six storeys over the concrete, tended by no one but you. … You pinch a basil leaf and smell it. You tie one bean vine a little higher. … The sun clears the far buildings and lays gold across your pots. The city can wake now; you were up first, and you spent it growing things. ……\n\nNow set the can down and let the rooftop soften. … Keep the wet-soil smell and the six-storey calm. … Come back to your breath, the chair, the ground floor of yourself. … Open your eyes when you are ready."),
("the-reading-child", "reading to a child who's falling asleep against me",
"Let your voice go quiet in your mind, and your eyes close softly. …… You are propped against a headboard in lamplight, reading aloud, and a child is falling asleep against your side. … Their head rests on your ribs; you can feel it grow heavier, page by page, as sleep pulls them down. … Their breathing slows and deepens — you can feel that too, a small warm tide against you. …… You keep reading, softer now. It doesn't matter what the words are anymore; what matters is the sound of you, steady and near. … The lamp makes a gold tent over the two of you. The rest of the house is dark and doesn't exist. … The child's hand is curled in your shirt like it grew there. … You reach the end of the page and just — stop. Listen. All the way asleep. … You sit very still, the book open on your knee, memorizing the weight of this — because some part of you knows, even inside the moment, that this is one of the ones you'll want back. … Stay in it. It's yours. ……\n\nNow ease the book closed without a sound. … Keep the small warm weight and the lamplight. … Come back gently to your own breath, your chair, the quiet. … Open your eyes when you are ready."),
]

# uniqueness gate: opening (first 40 chars) must be new across gold + candidates
existing = set()
for f in CAND.glob("*.json"):
    existing.add(json.loads(f.read_text())["text"][:40])
for line in GOLD.read_text().splitlines():
    if line.strip(): existing.add(json.loads(line)["text"][:40])

added = []
with GOLD.open("a") as gf:
    for sid, prompt, text in SCRIPTS:
        head = text[:40]
        assert head not in existing, f"opening collision: {sid}"
        existing.add(head)
        obj = {"id": sid, "prompt": prompt, "text": text,
               "src": f"candidates/claude-2026-07-07-b3", "tier": "gold-candidate",
               "license": "Original — drafted for Hearth (Sonali Maitra), not yet audited",
               "source_url": "", "note": f"Claude-drafted vivid gold candidate (batch 3). PENDING Sonali taste audit."}
        (CAND/f"{sid}.json").write_text(json.dumps(obj, ensure_ascii=False, indent=1))
        gf.write(json.dumps({"text": text, "prompt": prompt, "intake": prompt,
                             "src": f"candidates/{sid}", "tier": "gold"}, ensure_ascii=False)+"\n")
        added.append(sid)

# rebuild INDEX
allj = sorted(CAND.glob("*.json"))
idx = [f"# Gold candidates — vivid, prompt-matched ({len(allj)} so far, target 100)\n"]
for f in allj:
    d = json.loads(f.read_text())
    idx.append(f"\n## {d['id']}  ·  {len(d['text'].split())} words\n\n**Prompt:** _{d.get('prompt','')}_\n\n{d['text']}\n")
(CAND/"INDEX.md").write_text("\n".join(idx))
print(f"added {len(added)} scripts; candidates now {len(allj)}; A_gold now {sum(1 for l in GOLD.read_text().splitlines() if l.strip())} lines")
