#!/usr/bin/env python3
"""GOLD CANDIDATES batch 2 — heightened vividness. ADDS to the existing _candidates set
(does not delete batch 1), then rebuilds INDEX.md across everything.
Claude-drafted, prompt-matched; PENDING Sonali taste audit before promotion to gold.
"""
import json
from pathlib import Path

OUT = Path.home() / "Downloads/hearth-corpus/A-imagination/_candidates"
OUT.mkdir(parents=True, exist_ok=True)
SETTLE = ("Close your eyes, and let yourself arrive. …… One slow breath in through your nose … "
          "and a longer one out through your mouth. … Let the chair take your weight. … "
          "One more breath, and set down the day you were just in. ……")

SCRIPTS = [
("the-mountain-train", "riding a train through the mountains, watching it all roll by",
 SETTLE + """\n\nNow you are in a window seat on a train, and it is carrying you up through the mountains. … Feel the gentle rock and sway of the car, the steady clack and hum of the rails coming up through the floor and the seat into your body — that traveling rhythm that loosens everything. … The glass is cool against your forehead when you lean in. …… And out there the world unrolls and unrolls. Black pine forest climbing the slopes. A river far below, white where it breaks over the rocks, green where it pools. … The train swings into a curve and you can see the engine pulling you on ahead. … Then a tunnel — sudden dark, the roar closing in, your own face floating in the black glass — and out the far side into a blaze of light and a whole valley opened up below, fields like a quilt, a steeple, cloud-shadows dragging across it all. … You have nowhere to be but here, carried, watching. Let the mountains pull you on. ……\n\nNow let the window soften and the clacking rails grow faint. … Keep the loose, traveling ease in your body. … Come back to your breath, the chair, the still room. … Open your eyes when you are ready."""),

("candlelit-rain-reading", "reading in a candlelit room while rain falls outside",
 SETTLE + """\n\nNow you are curled in a deep chair in a small room, late, with a book open in your lap and a single candle burning beside you. … The flame leans and steadies, leans and steadies, and the whole room moves with it — gold light swelling up the walls and sinking back, shadows breathing. … Feel the weight of the open book against your knees, the soft give of the pages under your thumb. …… Outside the window it is raining — a steady, gentle rain, ticking on the glass and the sill, whispering in the dark leaves. … The room smells of warm wax and old paper and rain. … You read a line, and another, and the words go down easy and deep. … The candle ticks. The rain ticks. … There is nowhere else you are supposed to be, no light to answer to but this one small flame, no sound to mind but the rain. … Sink another inch into the chair. Turn the page. ……\n\nNow let the page blur gently and the candlelight soften. … Carry the hush and the warm gold with you. … Come back to your breath, your chair, the real room. … Open your eyes when you are ready."""),

("desert-stars", "lying out in the desert at night under a sky full of stars",
 SETTLE + """\n\nNow you are lying on your back in the open desert, deep in the night. … The day's heat is still rising up out of the sand and the rock beneath you, warming your back even as the air above goes cool and clean and dry on your face. … It is utterly silent — a vast, ringing silence so complete you can hear your own blood. …… And above you is the whole sky. Not a handful of stars — thousands, tens of thousands, flung from horizon to horizon, layer behind layer behind layer, until the black between them is more silver than black. … The Milky Way arches straight over you, a river of pale fire. … Watch long enough and a star tears loose and falls, a quick bright scratch across the dark, gone. … You feel yourself very small and very safe at once, a warm speck of life laid out under the whole turning universe, held by the warm ground. … Just breathe, and look up, and let it be this big. ……\n\nNow let the stars soften, and feel the warm sand hand you gently back. … Keep the great quiet and the bigness. … Come back to your breath, your room, the chair beneath you. … Open your eyes when you are ready."""),

("first-snowfall-window", "watching the first snow of winter fall, from a warm window",
 SETTLE + """\n\nNow you are standing at a window, warm, watching the first snow of the winter begin to fall. … At first it is almost nothing — a few flakes wandering down, too few to land. … Then more. Then all at once the air is full of it, fat slow flakes drifting and turning, more than you can follow, coming down out of a soft pewter sky. …… The world goes quiet under it. The rooftops take a first dusting of white; the dark branches catch and hold it; the street softens and rounds and goes clean. … Sound itself seems to muffle, wrapped in wool. … Your breath fogs a little circle on the cold glass and you wipe it clear with your sleeve to watch. … There is the particular wonder of the first snow — the year turning over, the whole tired world being quietly made new and white and soft while you stand here warm and watch it happen. … Stay, and watch it come down. ……\n\nNow let the snow soften toward the edges of sight. … Carry the hush and the new-made wonder. … Come back to your breath, your warm room, the chair. … Open your eyes when you are ready."""),

("lake-rowing-dawn", "rowing a small boat across a perfectly still lake at dawn",
 SETTLE + """\n\nNow you are in a small wooden rowboat in the middle of a lake, just at dawn, and the water is perfectly, glassily still. … You pull the oars, and feel them bite and the boat surge forward under you, and then the long quiet glide. … The drip of water off the lifted blades is the loudest thing for miles. …… Mist lies low on the water in long pale ribbons, and the boat slides through them. … The lake is a flawless mirror — the dark treeline, the pink-and-grey sky, all of it lying perfect and upside-down on the surface, so that you seem to be rowing through the sky itself. … Pull, and glide. … A loon calls somewhere in the mist, long and wavering and lonely-sweet, and the silence closes again. … The air is cold and smells of water and green. … Rest the oars. Let the boat coast to stillness and just sit, rocking faintly, in the middle of all that calm. ……\n\nNow let the lake soften and the mist thin. … Keep the deep, mirrored stillness. … Come back to your breath, the chair, the room. … Open your eyes when you are ready."""),

("hot-spring-night", "soaking in a natural hot spring at night, steam rising under the stars",
 SETTLE + """\n\nNow you are lowering yourself, slow, into a natural hot spring, out in the open, at night. … The heat closes over your legs, your waist, your shoulders — almost too hot for a second, and then exactly right, sinking straight into your muscles and loosening every knot it finds. … You let your head rest back on the smooth rock at the edge. …… Steam rises off the water all around you and curls up into the cold night air, and where the cold touches your face and the heat holds your body, you feel wonderfully, impossibly alive. … The water moves against your skin, silky, mineral, faintly sulfur-sweet. … And overhead — stars, sharp and countless in the black, and the steam drifting up to blur them. … Somewhere, the trickle of the spring feeding in. Otherwise, silence, and heat, and the cold clean night. … Let your arms float. Let the heat have you completely. ……\n\nNow, slowly, feel the warm water begin to set you down toward solid ground. … Keep the deep loosened heat in your muscles. … Come back to your breath, your room, the chair. … Open your eyes when you are ready."""),

("autumn-forest-walk", "walking through an autumn forest with the leaves coming down",
 SETTLE + """\n\nNow you are walking, slow and easy, along a path through a forest in the full blaze of autumn. … Above you and all around, the leaves have turned — gold, copper, scarlet, burnt orange — and the low sun pours through them so the whole woods glows as if lit from inside, a cathedral of fire-colored light. …… The leaves are coming down. One at a time, then a little gust, and a whole bright shower of them spinning and drifting through the slanted light, ticking softly as they land. … Underfoot they lie deep and dry, and every step is a rich crunch and rustle, and they smell of it — that good clean dust-and-cider smell of autumn woods. … The air is cool enough to taste, crisp at the back of your throat. … A squirrel ratchets up a trunk. Far off, crows. … Catch a falling leaf out of the air, if one comes near. Walk on through the gold, in no hurry, while the forest lets go all around you. ……\n\nNow let the bright woods soften and the falling leaves slow. … Carry the glow and the crisp clean air. … Come back to your breath, the chair, the room. … Open your eyes when you are ready."""),

("city-rooftop-night", "standing on a rooftop at night, the whole city of lights below",
 SETTLE + """\n\nNow you are standing on a rooftop, high above the city, late at night. … The air up here is cool and moves freely, lifting your hair, carrying the faint far-off hum of the streets below. … And spread out under you in every direction is the whole city, lit — a vast field of lights, gold and white and red, stretching to the dark edge of the horizon. …… Rivers of headlights crawl the avenues far below. Windows stand lit in a thousand towers — each one a life, a room, a kitchen, someone awake. … The big buildings rise around you, their tops red-blinking against the low orange glow the city throws up onto the clouds. … You feel the strange tender thing of looking down on so many lives at once — all of it humming on without you needing to do a thing, beautiful and indifferent and alive. … Up here you are apart from it and held by it both. … Lean on the rail. Take the whole glittering sweep of it. ……\n\nNow let the city soften to a blur of warm light. … Keep the cool free air and the wide tender calm. … Come back to your breath, the chair, the still room. … Open your eyes when you are ready."""),

("the-unhurried-day", "living a whole ordinary day as the calm, unhurried version of myself",
 SETTLE + """\n\nNow you are moving through an ordinary day — but you are living it as the unhurried version of yourself. The one who is not behind, not braced, not running ahead of her own feet. … See the morning. You finish the cup of coffee before you stand up; you actually taste it, warm and bitter-sweet. … The light is on the kitchen floor and you let yourself notice it. …… You do one thing at a time, all day. One. … When something goes a little wrong, you feel the old jolt rise — and it passes through you and out, and you simply handle the thing and move on, your breath still slow, your hands still loose. … Feel how strange and roomy it is, this not-hurrying — the trust that there is enough time, that you are allowed to be exactly where you are instead of three steps ahead. … See yourself at the end of this day: tired in the good, full way, not the frayed way. Nothing was lost by going at this pace. You did it all better, because you were actually there for it. ……\n\nNow let the day soften. … Carry the unhurried ease in your chest and your slow open hands — you can choose it any time you remember. … Come back to your breath, the chair, the room. … Open your eyes, unhurried."""),

("holding-a-sleeping-baby", "holding a sleeping baby, the whole warm sleeping weight of them",
 SETTLE + """\n\nNow you are sitting in a quiet, dim room, holding a sleeping baby against your chest. … Feel the whole warm weight of them, gone heavy and boneless with sleep, melted completely into you, trusting you with every ounce of themselves. … Their cheek is against your collarbone, impossibly soft and warm. …… Feel the quick small rise and fall of their breathing, faster than yours, and the flutter of it warm against your neck. … Now and then a tiny sigh, a soft suck, a twitch of the fingers curled against your shirt, and then deep stillness again. … They smell of milk and warmth and that clean, particular baby-scalp smell, and you find yourself breathing it in. … The whole loud world has narrowed to this one small warm bundle and the slow rocking and the dim and the hush. … Nothing in the universe needs you to be anywhere but here, holding this. … Let your own breathing slow to match the rocking. Let the tenderness fill your whole chest. ……\n\nNow let the room soften, but keep the warm weight and the tenderness. … Come back, gently, to your own breath, the chair, the quiet room. … Open your eyes when you are ready."""),

("slow-dance", "slow dancing with someone I love, late, music low",
 SETTLE + """\n\nNow you are slow dancing with someone you love, late in the evening, the music turned down low. … You are barely moving — just swaying, turning slowly in a small circle, your feet hardly leaving the floor. … Feel where you are touching: their hand warm in yours, your other hand resting at their back, the warmth of them all down the front of you. …… Your cheek rests against theirs, or against their shoulder, and you can feel them breathe, slow and easy, and you have fallen into breathing with them. … The song moves on, low and warm, and you sway with it. … There is nowhere to get to in this dance; it isn't going anywhere; it is only this — the swaying, the warmth, the held hand, the quiet song, this person, this small circle of floor. … You could stay here a long time. … Let yourself rest your full weight into the moment, into them. Let your eyes stay closed and just feel it. ……\n\nNow let the music fade gently, but keep the warmth and the held closeness. … Come back, slowly, to your own breath, your own room, the chair. … That warmth lives in you. … Open your eyes when you are ready."""),

("campfire-stars", "sitting at a campfire under the stars with people I love",
 SETTLE + """\n\nNow you are sitting at a campfire, out under the open stars, with people you love around you. … The fire is built up and burning well, and you can feel its heat on the fronts of your shins and your face while the cool night air rests against your back. … Watch the flames — the way they lean and twist and climb, gold and orange shot through with a flicker of blue at the base, and the sparks that lift off and spiral up and wink out among the stars. …… The fire snaps and pops; a log shifts and settles in a soft collapse of embers. The air is sweet with woodsmoke. … Around you, the easy voices of your people, a low laugh, a long comfortable silence that nobody needs to fill. … Lean back and the sky is enormous and crowded with stars above the firelight. … You are warm, and fed, and among your own, far from anything that could ask anything of you. … Hold a stick into the coals and watch it catch. Let the night and the fire and the company wrap all the way around you. ……\n\nNow let the fire burn low and soft in your mind. … Carry the warmth and the belonging out with you. … Come back to your breath, your chair, the room. … Open your eyes when you are ready."""),

("being-a-hawk", "being a hawk, riding a thermal high over the land",
 SETTLE + """\n\nNow you are not yourself watching a bird — this time you are the hawk, and you are high, high over the land, riding a warm rising column of air. … Feel your wings, held wide and still, the long feathers at their tips spread like fingers and trembling faintly as they read the wind. … You are barely working; the thermal lifts you, and you wheel slowly upward on it in a great patient spiral. …… Below you the whole country is laid out small and bright and clear — the green and gold patchwork of fields, the dark crowns of trees, a silver wink of river, the threads of roads. … Your eye is impossibly sharp; you can see a mouse move in the grass a thousand feet down. … The wind pours past you, cool and clean and endless, and you tilt one wing and slide sideways across the sky just to feel it answer. … There is no hurry and no fear up here — only the lift, the height, the long slow circle, and the whole world turning quietly far below. … Open your wings to the wind and let it carry you higher. ……\n\nNow begin to come back into your own shape and your own weight. … Let the wings become arms, the sky become the room. … Keep the hawk's wide calm and clear eye. … Come back to your breath, the chair, the floor. … Open your eyes when you are ready."""),

("the-bookstore-rain", "browsing a cozy old bookstore on a rainy afternoon",
 SETTLE + """\n\nNow you are inside a small old bookstore on a grey, rainy afternoon, and you have all the time in the world. … The shop is warm and a little cramped and wonderful — shelves to the ceiling, narrow aisles, books stacked on the floor and along the stairs, more books than anyone could ever read. … The whole place smells of it: old paper, dust, binding glue, a little rain tracked in. …… Outside the front window the rain comes down steady and the street is dark and shining, and in here it is dry and gold-lit and hushed. … You run a finger along a row of cracked spines, tip one out, feel the weight of it, let it fall open, read a line at random. … A clock ticks somewhere. The rain hisses softly on the glass. A floorboard creaks as you move deeper in. … There is nowhere you have to be and nothing you have to find — just the warm dim, the rain outside, the endless patient books, and the whole slow rainy afternoon to wander. … Pull down another. ……\n\nNow let the shelves soften and the rain grow faint. … Carry the warm hush and the unhurried afternoon. … Come back to your breath, the chair, the room. … Open your eyes when you are ready."""),

("fresh-sheets-summer", "lying down in fresh sheets by an open window on a summer night",
 SETTLE + """\n\nNow you are lying down into a bed made up with cool, fresh, clean sheets, on a warm summer night, with the window open. … Feel the sheets — cool and smooth and crisp against your skin, that particular clean-laundry crispness, as you stretch your legs all the way down into them and they slide cool against you. … Your head sinks into the pillow. …… Through the open window comes a soft warm breath of night air, moving the curtain gently, carrying in the smell of summer — cut grass, a little jasmine, warm earth cooling. … Far off, the sound of the night: a few crickets, a dog once, a car passing streets away and gone. … The day is fully done. Your body is heavy and loose and grateful to be lying down. … Each breath comes slower than the last. … There is nothing left to do today, nowhere to be, nothing to hold — only the cool sheets, the warm air, the soft dark, and the long slow slide down toward sleep. … Let yourself sink. ……\n\nNow, gently — without leaving the calm — let your awareness come back up toward the room. … Keep the heavy, grateful ease in your limbs. … Come back to your breath, the chair, the space around you. … Open your eyes, slow, when you are ready."""),
]

for sid, prompt, text in SCRIPTS:
    obj = {"id": sid, "prompt": prompt, "text": text.strip(),
           "src": "candidates/claude-2026-06-17-v2", "tier": "gold-candidate",
           "license": "Original — drafted for Hearth (Sonali Maitra), not yet audited",
           "source_url": "",
           "note": "Claude-drafted vivid gold candidate (prompt-matched). PENDING Sonali taste audit before promotion to gold."}
    (OUT / f"{sid}.json").write_text(json.dumps(obj, ensure_ascii=False, indent=1))

# rebuild INDEX across ALL candidates
allj = sorted(OUT.glob("*.json"))
idx = ["# Gold candidate scripts — VIVID, prompt-matched\n",
       f"_{len(allj)} scripts so far (target 100). Each renders a user-style PROMPT richly. "
       "Awaiting your taste audit — keep / kill / edit each._\n"]
for f in allj:
    d = json.loads(f.read_text())
    idx.append(f"\n## {d['id']}  ·  {len(d['text'].split())} words\n\n**Prompt:** _{d.get('prompt','')}_\n\n{d['text']}\n")
(OUT / "INDEX.md").write_text("\n".join(idx))
print(f"batch 2 added {len(SCRIPTS)}; total candidates now {len(allj)}")
