#!/usr/bin/env python3
"""GOLD CANDIDATE imagination scripts — vivid, prompt-matched (v2).
Each entry pairs a user-style PROMPT (the scene the user asks for) with a richly
rendered script that MATCHES it — committed, multisensory, specific. Diversity of
prompts is the cure for the corpus's single-template collapse.
Claude-drafted; PENDING Sonali taste audit before any promotion to gold.
Out: ~/Downloads/hearth-corpus/A-imagination/_candidates/*.json + INDEX.md
"""
import json, shutil
from pathlib import Path

OUT = Path.home() / "Downloads/hearth-corpus/A-imagination/_candidates"
if OUT.exists(): shutil.rmtree(OUT)          # replace the earlier open-handed batch
OUT.mkdir(parents=True, exist_ok=True)

SETTLE = ("Close your eyes, and let yourself arrive. …… One slow breath in through your nose … "
          "and a longer one out through your mouth. … Let the chair take your weight. … "
          "One more breath, and set down the day you were just in. ……")

# (id, prompt, body). body = the vivid scene; settle is prepended, return is per-script.
SCRIPTS = [
("the-finished-thing", "the morning after I finally finish the big thing I've been carrying",
 SETTLE + """\n\nNow it is a morning a few months from now — the morning after the thing is finally done. … The light is coming in low and gold across the floor, the particular quiet of very early, before anyone else is up. … You are warm. There is a cup in your hands and the heat of it seeps into your fingers; steam lifts off it and you can smell it. …… Feel how your shoulders sit this morning — lower than they have sat in months. The thing that has been pulling at the back of your mind, every hour, for so long — it has gone quiet. The quiet is enormous. You can feel it in your chest, like a held breath finally let go. …… Look down at your own hands. These are the hands that did it — page by page, day after day, coming back even when you didn't want to. And here you are, on the other side. … Let the pride come. The private kind, that you don't have to explain to anyone. ……\n\nNow let the morning soften and gold over. … Take the lowered shoulders with you — that exact feeling, waiting for you past the work. … Come back to your breath, the chair, the real room around you. … When you are ready, let your eyes open."""),

("thunderstorm-and-tea", "a thunderstorm rolling in while I'm warm and safe inside with tea",
 SETTLE + """\n\nNow you are deep in a soft chair by a tall window, and outside the sky has gone the color of slate and bruise. … The rain comes harder — you hear it drumming the glass and hissing in the gutters, a steady roar wrapping all the way around the warm, dim room. … A single lamp burns low beside you. … You hold a mug in both hands; the heat soaks into your fingers, and the steam curls up warm against your face — you can smell it, dark and good. …… Then a flash — the whole room goes white-blue for one held instant, every raindrop on the glass lit like a bead of glass itself — and you count … one … two … three … and the thunder arrives, a long low roll you feel in your chest as much as hear. … The drumming rain, the hot mug, the lamp, the safe dark room. You are exactly where you want to be while the whole sky comes apart out there. … Pull your feet up under you. Let the next roll of thunder move through you and out. ……\n\nNow let the storm soften toward the edges of hearing. … Keep the warmth of the mug in your hands. … Come back to your own breath, your own room, the chair beneath you. … Open your eyes when you are ready."""),

("warm-water-weightless", "floating weightless in warm water, completely held",
 SETTLE + """\n\nNow you are lying back in warm water — a still pool, a calm sea gone glassy at the end of the day, whichever rose up first when I said it. … It is exactly as warm as you would want. It holds you completely; you do nothing to float, the water does it for you. …… Feel the line where the water meets your skin — at your temples, your ears, so that sound goes soft and far and round. … Warmth moving the length of your arms, your legs, pooling in the small of your back. … Let your hands open under the surface. Let your fingers drift. … Feel the tiny rise and fall of your whole body with each breath, the water lifting you a half-inch and setting you down. …… Above you the sky is wide and going amber, and the last of the sun is a real warmth on your face and your closed eyes. … There is nothing to reach for. Nothing is being asked. Only warmth, and water, and your own slow breathing, and the enormous ease of being held without trying. ……\n\nNow, slowly, let the water begin to lower you toward solid ground. … Feel yourself grow a little heavier, a little more here — your back against the chair, your feet on the floor. … Bring the warmth back in your hands and your face. … One full breath. … Open your eyes, unhurried."""),

("the-pier-at-dawn", "standing alone at the end of a pier at dawn by a calm sea",
 SETTLE + """\n\nNow you are standing at the very end of a long wooden pier, barefoot, early in the morning. … The boards are cool and faintly damp under your feet, salt-rough, a little grit to them. … In front of you the water lies flat and silver, all the way out to a low seam where it meets a sky just beginning to pale. … The air is cool and clean and smells of salt and of the night that is just letting go. …… Listen. The water moves against the posts below you — a soft slap … and hush … slap … and hush. … Somewhere far off, one gull. Otherwise, nothing. You are the only one awake in the whole grey-gold world. …… Now the sun lifts its first hard line over the water, and a path of light comes straight across the sea toward you. … Feel it reach you — your face first, then your chest, then your hands on the cool rail — warmth arriving slowly into the cool. … The water begins to take the color: pewter, then rose, then a low burning gold. … Stand here and let the whole day begin, in no hurry at all to start it. ……\n\nNow take the wide quiet and the new warmth, and turn back down the pier. … Feel the boards carry you home. … Come back to your breath, your room, the chair. … Open your eyes when you are ready."""),

("walking-in-as-yourself", "walking into a hard meeting calm, steady, fully myself",
 SETTLE + """\n\nNow picture the door — the one you have been a little afraid of. The room, the meeting, the conversation, just on the other side of it. … You are standing just outside, but in this version you are calm. … Feel your feet, planted and even on the floor. Feel your breath, slow, coming from low in your belly. You are not bracing. You are simply here, ready. …… Now open the door and walk in as the steadiest version of yourself. … Feel how you carry it — spine long, shoulders down and easy, hands loose and open at your sides. You take your time crossing the room. You do not rush to fill the air. … When you speak, your voice comes from your chest, not your throat — low, unhurried, and it lands. … Notice you are not playing a part. This is just you, with the fear set down outside the door. … Feel the room steady itself around your steadiness. Feel what it is to be believed, because you believe yourself. ……\n\nNow let the room dissolve. You did not have to win anything in there — you only had to be this. … Carry the steadiness back in your spine and your open hands. … Come back to your breath, the chair, the quiet. … It is yours; it was always yours. … Open your eyes when you are ready."""),

("the-summit", "standing on the summit of a mountain I've just climbed, wind and the whole world below",
 SETTLE + """\n\nNow you are taking the last steps onto the summit of a mountain you have just climbed. … Your legs are burning in that good, earned way, your breath fast and deep, your heart big in your chest. … And then there is nothing higher — the ground falls away on every side, and the whole world opens out below you at once. … Ridge behind ridge behind ridge, blue going to paler blue going to the white haze of distance. … Far down, a valley, a thread of river catching light, the toy roofs of a town. …… The wind up here is constant and clean and loud, pushing at your jacket, cold on your hot face. … Open your arms to it. Let it take the heat off you. … The air is thin and bright and it tastes of stone and snow and sky. … You did this. Step by step, switchback by switchback, lungs and legs, you carried yourself all the way up here — and now you stand on top of it, with the wind and the enormous, ringing silence underneath the wind. … Turn slowly, all the way around, and take the whole horizon. ……\n\nNow set the summit in your memory, like a photograph you can keep. … Carry the bigness, and the earned, ringing pride. … Come back down to your breath, your chair, your room. … Open your eyes when you are ready."""),

("paddling-out-at-dawn", "paddling out into the ocean to surf, just at first light",
 SETTLE + """\n\nNow you are wading into the ocean at first light, board under your arm, the water cold and alive around your shins, then your thighs. … You lie down onto the board and start to paddle out, and the cold rushes along your forearms with every stroke. … The sea is grey-pink and breathing — long smooth swells lifting you up and setting you down, up and down, as you paddle into them. …… A wave stands up ahead of you; you pull hard, drive the nose through the lip, and burst out the back into the calm beyond — salt on your lips, your hair streaming, your whole body awake and stinging with cold and life. … Out past the break it goes quiet and glassy. You sit up on the board, straddling it, rising and falling on the slow swell. … The sun is just coming off the water, laying a band of fire across the whole sea toward you. … Behind you the empty beach; ahead, only ocean and light. … You are rinsed clean and completely here. …… Now feel a good one coming — turn, paddle, and feel the wave gather you up. ……\n\nNow let the sea lower you gently back to stillness. … Keep the awake, rinsed-clean feeling. … Come back to your breath, your room, the chair. … Open your eyes when you are ready."""),

("the-full-kitchen", "a warm, busy kitchen full of people I love, something good cooking",
 SETTLE + """\n\nNow you are in a kitchen, warm and full of people you love. … The oven has been on for hours and the whole room is warm with it, and the air is thick and wonderful — garlic, butter, something roasting, bread. … Steam fogs the lower corner of the window. … There is noise, all of it good: a pot lid rattling, someone laughing too loud at the table, a knife on a board, two conversations crossing. … You have a glass in your hand. Feel the cool of it against your warm palm. …… Someone bumps your shoulder going by and squeezes it. … Someone hands you a spoon to taste — feel the heat of it at your lips, the flavor blooming. … You don't have to do anything in particular. You are just in it — in the heat and the smell and the noise and the easy belonging of a room where everyone is glad you're there. … Look around at the faces, lit gold in the kitchen light. … Let yourself feel how much you love this, while it is happening, instead of only after. ……\n\nNow let the kitchen warm and blur and soften. … Carry the belonging and the warmth out with you. … Come back to your breath, your chair, your room. … Open your eyes when you are ready."""),

("earth-from-orbit", "floating in space, looking back at the whole Earth",
 SETTLE + """\n\nNow, impossibly, gently, you are floating in space — weightless, perfectly safe, turning slowly. … And below you, filling half the sky, is the whole Earth. … Blue. A blue so deep and luminous it seems lit from inside. … White cloud wrapped over it in long slow swirls; the brown and gold of a continent; the wrinkled silver of an ocean catching the sun. … It is silent. Utterly silent, and utterly still, and so beautiful it presses on your chest. …… Around it, the thinnest bright line of atmosphere — that whole fragile skin of air that everything alive is breathing right now. … And beyond, in every direction, black, and more stars than you have ever seen, hard and unblinking and without number. … You hang here between the stars and the blue world, weightless, and feel yourself go very quiet and very small and, somehow, completely at peace. … Watch the line of sunrise come around the curve of the Earth — a blade of gold racing across the dark side, lighting it as it goes. ……\n\nNow turn, slowly, and let yourself drift back down toward your own small warm life. … Keep the quiet, and the sense of the whole blue world held in the dark. … Come back to your breath, your body, your chair. … Open your eyes when you are ready."""),

("the-summer-meadow", "lying in a high summer meadow, sun and grass and the hum of insects",
 SETTLE + """\n\nNow you are lying on your back in a meadow, in the middle of high summer. … The grass is long and dry and warm beneath you, and it gives under your weight and cradles you. … Above you the sky is an enormous, simple blue, with two slow white clouds going nowhere. … The sun lies on you like a heavy warm blanket — on your face, your chest, the backs of your hands — and you can feel it loosening every muscle it touches. …… All around you is the sound of the meadow: the dry hum and saw of insects, near and far, rising and falling; the dry whisper of the grass when a little wind moves through it and lays it over in a long slow wave. … You can smell it — warm hay, crushed green, something flowering sweet nearby. … A grasshopper ticks past. … A bee works the air somewhere over your head. … There is nowhere to be and nothing to do but lie here and be warmed and held by the ground and let the long golden afternoon go on and on. ……\n\nNow let the meadow soften around you. … Keep the sun's warmth on your skin. … Come back, slowly, to your breath, the chair, the real room. … Open your eyes when you are ready."""),

("the-night-forest-snow", "walking alone through a snowy forest at night, lantern light",
 SETTLE + """\n\nNow you are walking, alone and unhurried, along a path through a forest at night, in falling snow. … The snow comes down thick and soundless through the dark, fat slow flakes turning gold as they drift through the light you carry. … Underfoot it is deep and clean; each step gives a soft, satisfying crunch and squeak, and then the silence closes again behind you. …… The trees stand all around in their white-loaded dark, huge and patient and kind. … Your breath puffs out in clouds. Your cheeks and nose are cold, a clean cold, but you are warm under your coat, warm at the core. … It is so quiet you can hear the snow itself — the faint endless hush of millions of flakes landing. … Stop a moment. Tip your head back and watch the snow come down out of the black into your light, on and on, without end. … You are the only one out here, and you are not lonely; you are held inside the great hushed patience of the winter woods. ……\n\nNow walk on, and let the forest and the snow grow gentle and far. … Carry the clean cold and the deep hush. … Come back to your breath, your warm room, the chair. … Open your eyes when you are ready."""),

("the-hands-that-make", "lost in making something with my hands, in total flow",
 SETTLE + """\n\nNow you are making something with your hands, and you are good at it, and you love it. … Let it be the thing that rose up — clay turning wet and cool under your palms on the wheel, a brush dragging loaded color across the tooth of the paper, dough warm and alive as you fold and press it. … Feel the material answer to you. Your hands already know the next move; they make it before you can think the word for it. …… You have stopped thinking in words at all. There is only this: the next small motion, and the next, and the quiet that opens up underneath them. … Time has gone soft and wide and you have no idea how long you have been here. … Watch the thing come into being under your hands — taking the shape it wants, becoming itself. … You are completely concentrated and completely at ease, both at once, and this — this absorbed, wordless ease — is one of the best feelings a person gets to have. … Stay in it. ……\n\nNow let the work come to a natural rest, and set it down, finished or not. … Bring your attention back to your own quiet hands. … Feel the chair, the floor, the room. … Carry the wordless ease back with you. … Open your eyes when you are ready."""),

("the-easy-reunion", "sitting with someone whose company is completely easy",
 SETTLE + """\n\nNow you are sitting down with someone whose company is completely easy — someone real or imagined, here or remembered — someone you never have to perform for. … See the place: a kitchen table, a porch step, a worn couch. See them already there, already glad you came. … Sit. … Feel what your body does in their company — your shoulders coming down off your ears, your breath going deeper, the guard you carry everywhere simply set down, because here you do not need it. …… You don't have to fill the silence. The quiet between you is warm, not awkward — the quiet of two people who are fine. … When you do speak you say the true thing, easily, because you already know it will be met with kindness. … Feel that rare double thing: being completely seen, and completely safe, at the same time. … There are few better feelings a person can have. Let yourself have it, all the way, for as long as you like. ……\n\nNow let the table and the company soften and fade. … Carry the dropped shoulders and the safety with you — they live in you, not only in them. … Come back to your breath, your room, the chair. … Open your eyes when you are ready."""),

("your-older-self-on-the-bench", "meeting my older, wiser self, who has already lived through what I fear",
 SETTLE + """\n\nNow you are sitting on a bench at the edge of a park, late in a golden afternoon. … And after a little while, someone comes and sits down beside you. … It is you. The older you, many years from now — the one who has already lived all the way through the thing you are afraid of. …… Look at them. See how they are. … Notice, first of all, that they are alright. More than alright — they are calm, and kind, and a little amused, the way people are when they remember being exactly where you sit now. … They are in no hurry at all. They have all the time in the world for you. … Let them tell you the one thing they most want you to know. Don't reach for it — let it come. It might be a single sentence. It might be a hand laid over yours. It might just be the look on their face. … Whatever it is, take it in. This is the voice of the part of you that already made it through. ……\n\nNow they smile, and the long afternoon goldens over. … Hold what they gave you. … Come back, slowly, to your own breath, your own age, your own room and chair. … Their calm is yours — it is waiting for you, up ahead. … Open your eyes when you are ready."""),

("cabin-and-the-snow", "warm in a small cabin late at night while it snows outside",
 SETTLE + """\n\nNow you are in a small cabin, late on a winter night, and outside the window the snow is coming down thick and slow and soundless in the dark. … But you are inside, and you are warm. … There is a fire, and you can hear it — the low tick and crackle and settle of the burning wood — and you can feel its heat reaching the side of your face and the backs of your hands. …… You are wrapped in something soft and heavy. … Through the window you watch the snow drift down through the spill of light from the cabin, turning gold as it falls and vanishing into the dark below. … It is so quiet you can hear the quiet — the whole world out there hushed and tucked under white. … There is nowhere to go tonight. Nothing can be asked of you out in all that snow. You are exactly where you should be: warm, and held, and still, beside the fire, while it snows and snows. … Let your breathing go as slow as the falling snow. ……\n\nNow let the cabin soften around you, but keep the fire's warmth on your face and hands. … Come back to your own breath, your own room, the chair. … Open your eyes when you are ready."""),
]

idx = ["# Gold candidate scripts — VIVID, prompt-matched (batch 2026-06-17 v2)\n",
       f"_{len(SCRIPTS)} scripts. Each is the rich rendering of a user-style PROMPT. "
       "Deliberately diverse to break the single-template collapse. Awaiting your taste audit — keep / kill / edit each._\n"]
for sid, prompt, text in SCRIPTS:
    obj = {
        "id": sid, "prompt": prompt, "text": text.strip(),
        "src": "candidates/claude-2026-06-17-v2", "tier": "gold-candidate",
        "license": "Original — drafted for Hearth (Sonali Maitra), not yet audited",
        "source_url": "",
        "note": "Claude-drafted vivid gold candidate (prompt-matched). PENDING Sonali taste audit before promotion to gold.",
    }
    (OUT / f"{sid}.json").write_text(json.dumps(obj, ensure_ascii=False, indent=1))
    idx.append(f"\n## {sid}  ·  {len(text.split())} words\n\n**Prompt:** _{prompt}_\n\n{text.strip()}\n")
(OUT / "INDEX.md").write_text("\n".join(idx))
print(f"wrote {len(SCRIPTS)} vivid prompt-matched candidates to {OUT}")
