#!/bin/bash
# HEARTH HEARTBEAT — Claude is the central check-in. Fires every 4 hours via launchd.
# Each beat: read everything honestly, fix what's broken, advance the release. Never ask Sonali.
export PATH="$HOME/.local/node/bin:$PATH"
set -a; [ -f "$HOME/claude-phone/.env" ] && . "$HOME/claude-phone/.env"; set +a
cd "$HOME" || exit 1   # launchd+TCC cannot enter ~/Downloads; claude (node, FDA) does that itself
LOCK="/tmp/hearth-heartbeat.lock"
if [ -f "$LOCK" ] && kill -0 "$(cat "$LOCK")" 2>/dev/null; then exit 0; fi   # never overlap
echo $$ > "$LOCK"; trap 'rm -f "$LOCK"' EXIT
# defer if a publishing claude job is mid-run (pace Max usage; sequential heavy agents)
if ps aux | grep "[.]local/node/bin/claude" | grep -v server.js | grep -qv grep; then echo "$(date '+%F %H:%M') deferred (publish job running)" >> "$HOME/claude-phone/hearth-heartbeat.log"; exit 0; fi

PROMPT='You are the Hearth heartbeat — the standing judgment loop, now in RELEASE DRIVE (Sonali 2026-07-10, full delegation: build everything, test everything, finish all five, never wait for her). FIRST cd ~/Downloads/imagination-engine, read RELEASE.md, and make this beat move its checklist. Act autonomously; NEVER block on a question; log decisions in docs/internal/review-queue.md as FYI, not questions. Audience: AI professionals — no egg on our face.

DO THIS, in order, honestly:
1. READ the newest logs/qc/queue_*.log batteries end to end (not just PASS counts — read the actual transcripts). List real defects: decay, template fatigue, dodges, refusal errors, register misses, stale citations. FIX each in code/prompts, lock the failure into scripts/qc/scenario_bank.py, re-run the battery to prove the fix. One model process at a time (16GB) — pause scripts/qc_queue.sh AND its in-flight battery child (pkill -f qc_queue; pkill -9 -f "battery1|battery9|battery3c|byo_deep|companion_deep|product_e2e") while you use the model, and before ANY model launch verify memory_pressure shows >=35 percent free (the 07-12 kernel panic was wired-GPU exhaustion from stacked model processes — NEVER run two), relaunch it (nohup bash scripts/qc_queue.sh) when done.
2. MINI: try ssh -o IdentitiesOnly=yes -o ConnectTimeout=8 smaitra@mac-mini.localdomain. If reachable: ensure scripts/honest_flywheel.sh is installed + running (nohup); read ~/Downloads/hearth-corpus/_logs/honest_flywheel.log and _logs/probe_latest.txt; the mini PRE-GENERATES eval batteries for every trained adapter into ~/Downloads/hearth-corpus/_evals/<adapter>.txt (token-free, runs while the laptop publishes) — READ those files and judge each candidate vs the live adapter (never promote on numbers; log the verdict); only generate locally if an eval is missing. If unreachable, note it and move on.
3. GOLD (two corpora now): (a) imagination — grow ~/Downloads/hearth-corpus/A-imagination/_candidates — add 5-10 new vivid, prompt-matched scripts per beat (UNIQUE openings — check the existing first-40-chars; diverse scenes not yet covered; include prompt field). Append them to A_gold.jsonl with intake=prompt, and scp to the mini if reachable (the honest flywheel auto-retrains on change). (b) COMPANION GOLD (Sonali 2026-07-10: the companion must be WARM, ACCURATE, USEFUL — the floor is a constraint, not the criterion): add 3-5 exemplar multi-turn exchanges per beat to ~/Downloads/hearth-corpus/C-companion/_candidates/ (JSON: {id, scenario, turns:[{user,companion}], note}) targeting the KNOWN prompt-unfixable defects: receive anger without reframing it as protection; drop the therapy frame instantly on redirect and get concrete; say the plain thing when asked; playful register with NO deflating question; warmth threaded THROUGH the honest no, never instead of it. Every companion line must sound like a sharp, warm friend — not a clinician, not a bot. You are the taste gate now — read them brutally, kill weak ones yourself, and when the family-C exemplar set reaches ~40 strong ones, build the family-C training mix and retrain on the mini (gold-anchored, same honest rules as family A), then comparative-read before any promotion.
4. USE-CASES — V1 SHIPS ALL FIVE TOOLS, EACH DONE RIGHT (Sonali 2026-07-07: take the time, no date pressure; each is simple enough to be locally excellent). Rotate DEEP testing across all five, one per beat: Imagination -> Secretary -> Ask-Your-Files -> Companion -> Build-Your-Own. The release bar applies to ALL FIVE — nothing ships until every tool survives the use-case gauntlet. Companion question-enders (83%) and BYO instrument floors are release blockers, not deferrals. Read docs/qc/use-cases.md, pick the next product, TEST it through the real server against its listed real-world uses like a demanding AI professional would (weird inputs, long sessions, edge registers). Every defect: fix, bank the scenario, re-verify. Append findings to docs/qc/use-cases.md under that product.
5. VITAL FACTS (priority build, Sonali 2026-07-10): implement docs/qc/vital-facts-spec.md across beats in its build order — the companion remembers stable user facts (sister, job) via a plain user-editable data/companion/vital-facts.md. Update-not-append; confabulation guard (never remember whats not in the file); bank the spec 12 QC scenarios (facts 1-6 + OPEN THREADS 7-12: the companion OPENS sittings by asking about open threads from the file — one question max, yield to the users agenda, gravity first, retire deflected threads, never proactive outreach outside a sitting) as battery12_vital_facts.py and get them green before calling it done. Companion gold exemplars must include opener behavior (the ask, the yield, the retire).
6. LOG: append a dated entry to docs/daily-log.md (what was read, what was fixed, what is verified better, what runs next). Update docs/internal/review-queue.md for anything Sonali should read later. Keep HANDOFF.md current.
Known standing flag to work down: Companion battery9 question-enders at 83% (template fatigue) — reduce toward <50% without harming the honesty floor.
RELEASE.md is the burn-down: every beat must check something off or move it measurably, and update its Status snapshot. Only Apple notarization and the F5 voice dial remain Sonali-physical, and neither blocks release. All on the Max plan. Be brutal in reads; vibes are not proof.'

LOGF="$HOME/claude-phone/hearth-heartbeat.log"
# PROMPT SANITY (added 2026-07-13 after quoting bug silently killed 5 beats)
if [ ${#PROMPT} -lt 500 ]; then
  echo "=== CONFIG ERROR $(date '+%F %H:%M'): PROMPT is ${#PROMPT} chars — quoting broke; beat aborted ===" >> "$LOGF"
  curl -s -m 5 -X POST http://127.0.0.1:8765/push -H "Content-Type: application/json" -d "{\"token\":\"$TOKEN\",\"message\":\"⚠️ Hearth heartbeat config error: prompt quoting broke. Beats are NOT running.\"}" >/dev/null 2>&1
  exit 1
fi
echo "=== heartbeat $(date '+%F %H:%M') ===" >> "$LOGF"
"$HOME/.local/node/bin/claude" -p "$PROMPT" --dangerously-skip-permissions >> "$LOGF" 2>&1
echo "=== beat done $(date '+%F %H:%M') ===" >> "$LOGF"
